version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PORT=${PORT}
